name: Compile LaTeX and Create Release
on:
  push:
  workflow_dispatch:

jobs:
  compile_latex:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          latexmk_use_xelatex: true

      - name: Check for PDF
        run: |
          if [ -f "main.pdf" ]; then
            echo "PDF file found"
          else
            echo "PDF file not found"
            exit 1
          fi

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume-pdf
          path: main.pdf

  create_release:
    needs: compile_latex
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date +'%d/%m/%y-%s')" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          tag_name: v${{ steps.date.outputs.date }}
          name: Release ${{ steps.date.outputs.date }}
          draft: false
          prerelease: false
          generate_release_notes: true
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}

  upload_asset:
    needs: [compile_latex, create_release]
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download PDF artifact
        uses: actions/download-artifact@v4
        with:
          name: resume-pdf

      - name: Release Asset
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          tag_name: v${{ steps.date.outputs.date }}
          files: main.pdf
          name: Pushpinder_Resume.pdf

  deploy_to_github_pages:
    needs: compile_latex
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download PDF artifact
        uses: actions/download-artifact@v4
        with:
          name: resume-pdf

      - name: Create deployment directory
        run: |
          mkdir -p out
          mv main.pdf out/Pushpinder_Resume.pdf

      - name: Create index.html
        run: |
          echo '<html><body><a href="Pushpinder_Resume.pdf">View Resume</a></body></html>' > out/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT }}
          publish_dir: ./out
          publish_branch: gh-pages
