name: Compile LaTeX and Create Release
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  workflow_dispatch:

jobs:
  compile_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache LaTeX build
        uses: actions/cache@v3
        with:
          path: |
            ~/.latexmk
            ./resume.aux
            ./resume.fdb_latexmk
            ./resume.fls
            ./resume.log
            ./resume.out
            ./resume.toc
          key: latex-${{ runner.os }}-${{ hashFiles('resume.tex') }}
          restore-keys: |
            latex-${{ runner.os }}-

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume.tex
          latexmk_use_xelatex: true

      - name: Check for PDF
        run: |
          if [ -f "resume.pdf" ]; then
            echo "PDF file found"
          else
            echo "PDF file not found"
            exit 1
          fi

      - name: Get current date and branch
        id: metadata
        run: |
          echo "date=$(date +'%Y-%m-%d-%H%M')" >> $GITHUB_OUTPUT
          echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Create release and deploy (if master branch)
        if: github.ref == 'refs/heads/master'
        run: |
          # Rename PDF for release
          cp resume.pdf "Devesh's Resume.pdf"
          
          # Create release with asset
          gh release create "v${{ steps.metadata.outputs.date }}" \
            --title "Release - ${{ steps.metadata.outputs.branch }} - ${{ steps.metadata.outputs.date }}" \
            --notes "Automated resume build" \
            "Devesh's Resume.pdf"
          
          # Prepare for GitHub Pages
          mkdir -p out
          cp resume.pdf out/Devesh_Resume.pdf
          echo '<html><body><a href="Devesh_Resume.pdf">View Resume</a></body></html>' > out/index.html
          
          # Deploy to GitHub Pages
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add out/
          git commit -m "Deploy resume to GitHub Pages" || exit 0
          git push origin HEAD:gh-pages --force
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Create branch-specific release (if not master)
        if: github.ref != 'refs/heads/master'
        run: |
          # Rename PDF for release
          cp resume.pdf "Devesh's Resume.pdf"
          
          # Create release with asset
          gh release create "v${{ steps.metadata.outputs.date }}-${{ steps.metadata.outputs.branch }}" \
            --title "Release - ${{ steps.metadata.outputs.branch }} - ${{ steps.metadata.outputs.date }}" \
            --notes "Automated resume build from ${{ steps.metadata.outputs.branch }} branch" \
            "Devesh's Resume.pdf"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume-pdf
          path: resume.pdf
